export const API_SCHEMA_VERSION = 10;
export const RELAY_RELEASE = "phase5-model-managed-output-1";

export const WORKER_API_CATALOG = [
  {
    method: "GET",
    path: "/v1/health",
    purpose: "Workerとschemaの疎通確認",
    auth: "none_phase0",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/admin/diagnostics",
    purpose: "所有者向けの秘密除外互換・運用診断",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/admin/maintenance/retention/preview",
    purpose: "保持期限掃除候補の本文なしpreview",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/admin/maintenance/retention/run",
    purpose: "保持期限掃除の冪等な手動実行",
    auth: "owner",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/admin/devices",
    purpose: "所有者向け端末一覧",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/admin/devices/revoke-all",
    purpose: "全端末資格情報の一括失効",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/admin/devices/cleanup-expired",
    purpose: "期限切れ端末資格情報の整理",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/standby-snapshots",
    purpose: "本体から暗号化待機snapshotを世代登録",
    auth: "owner",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/standby-snapshots",
    purpose: "端末向け安全な待機snapshot manifest一覧",
    auth: "device",
    implemented: true,
  },
  {
    method: "DELETE",
    path: "/v1/standby-snapshots/{standby_snapshot_id}",
    purpose: "待機snapshot本文の所有者削除",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/standby-snapshots/{standby_snapshot_id}/activate",
    purpose: "待機snapshotからplannedまたは障害旅行を冪等開始",
    auth: "device",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/standby-snapshots/{standby_snapshot_id}/external-ai-export",
    purpose: "明示同意後に待機snapshotの選択ペルソナを外部AI向け文面化",
    auth: "device",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/travel-sessions/{travel_session_id}/personas/{persona_id}/external-ai-export",
    purpose: "明示同意後に独立モード開始時点の選択ペルソナを外部AI向け文面化",
    auth: "device",
    implemented: true,
  },
  {
    method: "PUT",
    path: "/v1/provider-profiles/{credential_profile_id}",
    purpose: "Cloudflare Secretと分離した資格情報プロファイルの登録・更新",
    auth: "owner",
    implemented: true,
  },
  {
    method: "DELETE",
    path: "/v1/provider-profiles/{credential_profile_id}",
    purpose: "資格情報プロファイルの無効化",
    auth: "owner",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/provider-profiles",
    purpose: "端末・本体向け秘密除外資格情報プロファイル一覧",
    auth: "device_or_owner",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/provider-profiles/{credential_profile_id}/models",
    purpose: "端末・本体向け資格情報プロファイル別の利用可能モデル・能力・料金確認状態一覧",
    auth: "device_or_owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/pairing-codes",
    purpose: "短時間・単回利用の端末ペアリングコード発行",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/devices/pair",
    purpose: "ペアリングコードを端末資格情報へ交換し、有効な同一端末は資格情報を更新",
    auth: "pairing_code",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/devices/refresh",
    purpose: "端末資格情報のローテーション",
    auth: "refresh_token",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/devices/{device_id}/revoke",
    purpose: "端末資格情報の失効",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/devices/self/revoke",
    purpose: "端末自身の資格情報を失効して忘れる",
    auth: "device",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/travel-sessions",
    purpose: "単一または複数ペルソナsnapshotの出発登録",
    auth: "owner",
    implemented: true,
  },
  {
    method: "PUT",
    path: "/v1/travel-sessions/{travel_session_id}/route",
    purpose: "単一ペルソナの現在プロバイダ・モデルを冪等変更",
    auth: "device",
    implemented: true,
  },
  {
    method: "PUT",
    path: "/v1/travel-sessions/{travel_session_id}/personas/{persona_id}/route",
    purpose: "複数ペルソナセッションのペルソナ別経路変更",
    auth: "device",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/travel-sessions/current",
    purpose: "端末向けの現在セッション取得",
    auth: "device",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/travel-sessions/{travel_session_id}/personas/{persona_id}/events",
    purpose: "複数ペルソナセッションのペルソナ別差分イベント取得",
    auth: "device",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/travel-sessions/{travel_session_id}/events",
    purpose: "ペルソナ別の差分イベント取得",
    auth: "device",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/travel-sessions/{travel_session_id}/usage-summary",
    purpose: "既知料金・金額不明件数・cache利用量・残予算の取得",
    auth: "device",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/travel-sessions/{travel_session_id}/messages",
    purpose: "選択中プロバイダへの冪等なテキスト会話SSE",
    auth: "device",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/message-requests/{client_message_id}",
    purpose: "切断後の要求確定状態を再照会",
    auth: "device",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/travel-sessions/{travel_session_id}/export",
    purpose: "経路・cache・料金receiptを含む署名付き帰宅bundle v3生成",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/travel-sessions/{travel_session_id}/return/start",
    purpose: "オンライン帰宅を開始し新規送信を停止",
    auth: "owner",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/travel-sessions/{travel_session_id}/return/manifest",
    purpose: "ペルソナ別帰宅高水位と利用状況を取得",
    auth: "owner",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/travel-sessions/{travel_session_id}/return/chunks",
    purpose: "ペルソナ別の署名付き未取込差分を取得",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/travel-sessions/{travel_session_id}/return/ack",
    purpose: "ローカル確定済み帰宅cursorを冪等確認",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/travel-sessions/{travel_session_id}/personas/{persona_id}/emergency-reclaim",
    purpose: "対象ペルソナのtravel送信を停止し分岐可能性を記録",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/travel-sessions/{travel_session_id}/close",
    purpose: "帰宅済み化と本文削除期限確定",
    auth: "owner",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/maintenance/retention",
    purpose: "保持期限が到来したセッション本文の削除",
    auth: "owner",
    implemented: true,
  },
  {
    method: "DELETE",
    path: "/v1/travel-sessions/{travel_session_id}/content",
    purpose: "旅行セッションのクラウド本文削除",
    auth: "owner",
    implemented: true,
  },
  {
    method: "GET",
    path: "/v1/phase0/stream",
    purpose: "remote Worker Streamsの合成SSE検証",
    auth: "phase0_validation_token",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/phase0/live/validate",
    purpose: "承認済み実APIのワンショット検証",
    auth: "phase0_validation_token",
    implemented: true,
  },
  {
    method: "POST",
    path: "/v1/phase0/d1/validate",
    purpose: "remote D1のatomic batch・rollback・差分検証",
    auth: "phase0_validation_token",
    implemented: true,
  },
  {
    method: "DELETE",
    path: "/v1/phase0/d1/validate",
    purpose: "remote D1の合成検証データ削除",
    auth: "phase0_validation_token",
    implemented: true,
  },
] as const;
